
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function GuidesPage() {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-headline text-2xl">Guides</CardTitle>
        <CardDescription>
          Step-by-step tutorials to help you accomplish specific tasks.
        </CardDescription>
      </CardHeader>
      <CardContent className="prose prose-stone dark:prose-invert max-w-none">
        <h3>Analyzing Your First Log File</h3>
        <p>
          This guide will walk you through the process of submitting your first log file for analysis, from pasting the content to interpreting the results generated by the default agent workflow.
        </p>

        <h3>Building a Custom Agent Workflow</h3>
        <p>
          Learn how to use the Agentic Workflow Builder to create a custom pipeline. This guide covers adding, removing, and reordering agents to tailor the analysis process to your specific needs. You'll also learn how to sync your custom workflow with the main dashboard.
        </p>

        <h3>Fine-Tuning a Summarizer Agent</h3>
        <p>
          This tutorial shows you how to fine-tune the "Summarizer Agent" on your own dataset of logs and summaries. You'll learn how to prepare a dataset, start a fine-tuning job, and monitor its progress.
        </p>
        
        <h3>Setting Up a Jira Connector</h3>
        <p>
          Learn how to connect your LogAlot instance to Jira to automatically create bug reports and tickets from an AI analysis.
        </p>
      </CardContent>
    </Card>
  );
}
